export const BASEURL: string = 'https://fiturjc.lavandadelpatio.es/api/';
export const BASEURL_IMAGE: string = 'https://fiturjc.lavandadelpatio.es';
export const USER_BASEURL: string = BASEURL + 'user/';
export const USER_REGISTER: string = BASEURL + 'register';
export const ADMIN_COURSEURL: string = BASEURL + 'admin/course/';
export const ADMIN_USERURL: string = BASEURL + 'admin/';
export const COURSE_BASEURL: string = BASEURL + 'course/';
export const SCHEDULE_BASEURL: string = BASEURL + 'schedules/';
export const FACILITIES_BASEURL: string = BASEURL + 'facilities';
